# This creates secrets for the Aqua components. It is written as a pre-install hook. 
# A pre-install hook is run before the rest of the chart is loaded.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  password: {{ .Values.db.password | b64enc | quote }}

