apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-gateway
  labels:
    app: {{ template "fullname" . }}
    component: {{ template "fullname" .}}-gateway
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"      
spec:
  ports:
    - port: {{ default 3622 .Values.gateway.servicePort}}
  selector:
    app: {{ template "fullname" . }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-gateway
  labels:
    app: {{ template "fullname" . }}
    component: {{ template "fullname" .}}-gateway
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      name: {{ template "fullname" . }}-gateway
    spec:
      serviceAccount: {{ template "fullname" . }}
      containers:
      - name: {{ template "fullname" . }}-gateway
        image: "{{.Values.gateway.image}}:{{.Values.imageTag}}"
        imagePullPolicy: {{default "" .Values.pullPolicy | quote }}        
        env:
          - name: SCALOCK_GATEWAY_PUBLIC_IP
            value: {{ template "fullname" . }}-gateway
          - name: SCALOCK_DBUSER
            value: "postgres"
          - name: SCALOCK_DBPASSWORD
            valueFrom: 
              secretKeyRef:
                # name: {{ template "fullname" . }}-secret
                name: aqua-db                
                key: password
          - name: SCALOCK_DBNAME
            value: "scalock"
          - name: SCALOCK_DBHOST
            value: {{ template "fullname" . }}-db
          - name: SCALOCK_DBPORT
            value: "{{.Values.db.servicePort}}"
          - name: SCALOCK_AUDIT_DBUSER
            value: "postgres"
          - name: SCALOCK_AUDIT_DBPASSWORD
            valueFrom: 
              secretKeyRef:
                name: {{ template "fullname" . }}-secret
                key: password
          - name: SCALOCK_AUDIT_DBNAME
            value: "slk_audit"
          - name: SCALOCK_AUDIT_DBHOST
            value: {{ template "fullname" . }}-db
          - name: SCALOCK_AUDIT_DBPORT
            value: "{{.Values.db.servicePort}}"
        ports:
        - containerPort: {{ default 3622 .Values.db.containerPort}}
