apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-db
  labels:
    app: {{ template "fullname" . }}
    component: {{ template "fullname" .}}-db
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"    
spec:
  ports:
    - port: {{ default 5432 .Values.db.servicePort}}
  selector:
    app: {{ template "fullname" . }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-db
  labels:
    app: {{ template "fullname" . }}
    component: {{ template "fullname" .}}-db
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      name: {{ template "fullname" . }}-db
    spec:
      serviceAccount: {{ template "fullname" . }}
      containers:
      - name: {{ template "fullname" . }}-db
        image: "{{.Values.db.image}}:{{.Values.imageTag}}"
        imagePullPolicy: {{default "" .Values.pullPolicy | quote }}        
        env:
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: {{ template "fullname" . }}-secret
                # name: aqua-db
                key: password
        ports:
        - containerPort: {{.Values.db.containerPort}}
