apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-web
  labels:
    app: {{ template "fullname" . }}
    component: {{ template "fullname" .}}-web
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"    
spec:
  ports:
    - port: {{ default 8080 .Values.web.servicePort }}
  selector:
    app: {{ template "fullname" . }}
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-web
  labels:
    app: {{ template "fullname" . }}
    component: {{ template "fullname" . }}-web
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"      
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-web
      name: {{ template "fullname" . }}-web
    spec:
      serviceAccount: {{ template "fullname" . }}          
      containers:
      - name: {{ template "fullname" . }}-web
        image: "{{.Values.web.image}}:{{.Values.imageTag}}"
        imagePullPolicy: {{default "" .Values.pullPolicy | quote }}        
        env:
          - name: SCALOCK_DBUSER
            value: "postgres"
          - name: SCALOCK_DBPASSWORD
            valueFrom: 
              secretKeyRef:
                name: {{ template "fullname" . }}-secret
                key: password
          - name: SCALOCK_DBNAME
            value: "scalock"
          - name: SCALOCK_DBHOST
            value: {{ template "fullname" . }}-db
          - name: SCALOCK_DBPORT
            value: "{{.Values.db.servicePort}}"
          - name: SCALOCK_AUDIT_DBUSER
            value: "postgres"
          - name: SCALOCK_AUDIT_DBPASSWORD
            valueFrom: 
              secretKeyRef:
                # name: {{ template "fullname" . }}-secret
                name: aqua-db                
                key: password
          - name: SCALOCK_AUDIT_DBNAME
            value: "slk_audit"
          - name: SCALOCK_AUDIT_DBHOST
            value: {{ template "fullname" . }}-db
          - name: SCALOCK_AUDIT_DBPORT
            value: "{{.Values.db.servicePort}}"
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket-mount
        ports:
        - containerPort: {{ default 8080 .Values.web.containerPort}}
      volumes:
        - name: docker-socket-mount
          hostPath:
            path: /var/run/docker.sock        