# This creates  for the Aqua components. It is written as a pre-install hook. 
# A pre-install hook is run before the rest of the chart is loaded.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}
  annotations:
    "helm.sh/hook": pre-install
imagePullSecrets:
- name: {{ .Values.imagePullSecretName }}
